[versions]

mockito-inline = "5.2.0"
wiremock = "3.9.1"
grpcmock = "0.14.0"

plugin-grgit = "5.2.2"
plugin-jreleaser = "1.13.1"
plugin-micronaut = "4.4.2"
plugin-google-protobuf = "0.9.4"

[libraries]
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito-inline" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }
grpcmock-junit5 = { module = "org.grpcmock:grpcmock-junit5", version.ref = "grpcmock" }

[bundles]

[plugins]
grgit = { id = "org.ajoberstar.grgit:grgit-gradle", version.ref = "plugin-grgit" }
jreleaser = { id = "org.jreleaser:jreleaser-gradle-plugin", version.ref = "plugin-jreleaser" }
micronaut = { id = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "plugin-micronaut" }
google-protobuf = { id = "com.google.protobuf:protobuf-gradle-plugin", version.ref = "plugin-google-protobuf" }
