name: Java CI with Gradle (Kotlin)

on: [push, pull_request]
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload gRPC jar
        uses: actions/upload-artifact@v4
        with:
          name: micronaut-api-gateway-grpc
          path: micronaut-api-gateway-grpc/build/libs/micronaut-api-gateway-grpc.jar

      - name: Upload HTTP jar
        uses: actions/upload-artifact@v4
        with:
          name: micronaut-api-gateway-http
          path: micronaut-api-gateway-http/build/libs/micronaut-api-gateway-http.jar
